### ISSUE TITLE
There are no releases to install from.

### ISSUE THREAD

**Issue by kubaPod** [WolframResearch/MongoLink#1]
ReadME.me suggests to go to GH releases page in order to install the paclet. Yet the list is empty.

**Comment by arnoudbuzing** [comment]
I am checking to see what's going on. Thanks for pointing this out.

**Comment by arnoudbuzing** [comment]
@kubaPod : I uploaded a recent MongoLink paclet file. This should probably be happening in a more automated fashion, but for now I think this addresses your question?

**Comment by kubaPod** [comment]
@arnoudbuzing It does otoh I am confused because this paclet already is included in Mathematica v12+

     PacletFind["MongoLink"][[1]]["Location"] 
> "C:\\Program Files\\Wolfram Research\\Mathematica\\12.1\\SystemFiles\\Links\\MongoLink"

If that is expected then information about which Mathematica version contains which MongoLink version could be included in the ReadMe.
